[package]
name = "rublas"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
rand = "0.9.1"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "matmul_benchmark"
harness = false